### ISSUE TITLE
plugin checklist for nutaiga

### ISSUE THREAD

**Issue by ineeee** [nojusr/Taigabot3#1]
to get a working (nu)taigabot we need to have the following plugins:

- [ ] 4chan
- [ ] calculator (.wa, .calc)
- [ ] choose
- [ ] countdown
- [ ] define (.dictionary)
- [ ] duckduckgo
- [ ] google
- [ ] hashtags (.r, .f, #word)
- [x] lastfm
- [ ] ping
- [x] quote
- [ ] spotify
- [ ] soundcloud
- [ ] tell
- [ ] url titles
- [ ] vimeo
- [ ] weather
- [ ] youtube
- [ ] wikipedia

theyre the most common imo

**Comment by k-e-l-p** [comment]
figure we need to have wolframalpha too

**Comment by k-e-l-p** [comment]
hashtags are ez to implement will add setting to specifiy hashtag starting char
we already have lastfm and quotes.

**Comment by ineeee** [comment]
the wolfram alpha plugin is .calc

**Comment by k-e-l-p** [comment]
Updated README.org to list changes
