### ISSUE TITLE
Make users case insensitive in db

### ISSUE THREAD

**Issue by 676339784** [nojusr/Taigabot3#11]
For example, `.q add test alpha` and `.q add TEST bravo` would result in quotes being attributed to different users. Think it makes most sense if we make users case insensitive.

**Comment by ineeee** [comment]
case-sensitive has a different meaning in irc than in python. for a proper implementation we'd have to check what irc casemapping the server supports.

see `ISUPPORT`'s `CASEMAPPING` for details.

**Comment by ineeee** [comment]
reopening cuz only `.q` was patched (according to adrift)

**Comment by k-e-l-p** [comment]
.q is case-insensitive, everything seems to work

**Comment by ineeee** [comment]
https://github.com/nojusr/paprika/issues/11#issuecomment-514018335

according to adrift, the whole other set of user commands are still case-sensitive
