### ISSUE TITLE
many issues

### ISSUE THREAD

**Issue by ineeee** [nojusr/Taigabot3#14]
- kicking the bot makes it need a restart for some reason
- does not respond to invites
- `.yt` broke the same day it became available

edit: this isnt separate issues because they're too many and i don't want to spam

**Comment by ineeee** [comment]
also, the owner can't disable conflicting commands. it would be nice to disable `.yt` or `.wa` when other bots do it properly.

**Comment by ineeee** [comment]
the google search randomly doesn't return anything.

**Comment by ineeee** [comment]
bot doesnt respond to ctrl+c or any kill signal. can only be stopped (properly) if a global admin uses `.stop`

**Comment by 676339784** [comment]
> bot doesnt respond to ctrl+c or any kill signal. can only be stopped (properly) if a global admin uses `.stop`

i think that's just you

as many issues as paprika has right now at least i can stop it with ctrl-c

**Comment by k-e-l-p** [comment]
ok, I'm gonna outline some issues:
- .yt wasn't working on prod due to a couple of reasons: 
    -  There's a quota to how many API youtube requests that the bot can make within a week, I exceeded said quota when testing.
    - I didn't configure the API key properly, i.e I made it only so that my home IP address could use it, this  has been fixed
Right now .yt works perfectly and without issue.
- The bot does not autorejoin upon being kicked
   - Obviously this needs a fix, will work on this after writing this comment
- Plugins cannot be disabled/turned off while running
    - I'm not exactly sure about this, I think that wednesday did implement this ability, and we just don't know about it, either way, if it's implemented, i will disable .wa and .yt, otherwise, I will implement it in admin.py or gadmin.py
- Google search randomly does not return results
    - Again, a bug that needs fixing. The main issue is that the HTML parser randomly does not find the right elements, throws an exception, which is caught, and the plugin tries to make another request, which _sometimes_ works. This is a crummy fix, and a better solution is required. This is second on my list of today's fixes

> bot doesnt respond to ctrl+c or any kill signal. can only be stopped (properly) if a global admin uses .stop

The bot's core responds to ctrl+c, which _mostly_ shuts down cleanly, although there are a couple of event listeners/timed infinte loops that don't. I think that those need to be wrapped in a try/except KeyboardInterrupt statement.

**Comment by k-e-l-p** [comment]
@inexist3nce I just checked, there is a command that can disable other commands, events, and sieves.
Look in gadmin.py, line 51
```python
@hook.hook('command', ['gdisable', 'genable'], gadmin=True, autohelp=True)
async def g_genable_gdisable(client, data):
    """
    .genable/.gdisable <list/commands/events/sieves> -- Lists, enables or
    disables commands, events and sieves.
    """
    event_vals = list(client.bot.plugs['event']...
```

**Comment by ineeee** [comment]
NICE that's everything fixed, i'm closing the issue.

> @inexist3nce I just checked, there is a command that can disable other commands, events, and sieves.
> Look in gadmin.py, line 51

i meant like the channel owner, not the bot owner. adrift can disable taigabot things even as a non-gadmin because he owns the chan (does taiga check +q?)

**Comment by ineeee** [comment]
- [x] answering invites
- [x] youtube search has broken api
- [x] disabling commands
- [ ] google search doesnt search sometimes
- [x] ~ctrl-c doesnt work~ i bet its my stupid terminal

**Comment by k-e-l-p** [comment]
closing this issue and moving the one google search related issue to another issue
