### ISSUE TITLE
youtube.py randomly fails to parse incoming JSON

### ISSUE THREAD

**Issue by k-e-l-p** [nojusr/Taigabot3#16]
```python
Task exception was never retrieved
future: <Task finished coro=<ytsearch() done, defined at /home/kelp/paprika/plugins/youtube.py:90> exception=KeyError('videoId')>
Traceback (most recent call last):
  File "/home/kelp/paprika/plugins/youtube.py", line 135, in ytsearch
    vid_id = first_item['id']['videoId']
KeyError: 'videoId'
```

**Comment by ineeee** [comment]
maybe the api is returning channel/livestreams in the search results and they dont have `videoId`

**Comment by k-e-l-p** [comment]
check that commit, the random failures seem to arise due to a couple of reasons:
- when searching, the first result might be a channel, (with no `videoId`), this has been resolved by changing a couple of settings in the request
- a video might have their likes/dislikes disabled, which means that no JSON value for likes/dislikes is provided, this is now handled.
