### ISSUE TITLE
Add configuration parser

### ISSUE THREAD

**Issue by adedomin** [nojusr/Taigabot3#19]
the config format should not be JSON, it likely could be replaced with a preprocessed ini parser (configparser) or completely using TOML.

We Should also add a proper arg parser instead of the config just expected to exist at the root of the repo

**Comment by k-e-l-p** [comment]
JSON is an agnostic data-representation format, this means that it can be used for anything, including configuration files. It's also included in python by default so that's why we're using it for configuration. This isn't an enterprise tier project that needs everything to be done custom.
