### ISSUE TITLE
name for new bot

### ISSUE THREAD

**Issue by ineeee** [nojusr/Taigabot3#2]
we need to decide on a cute name for the new bot. current ideas:

- thursday
- nuthursday
- emmma
- nutaiga
- manabu

**Comment by k-e-l-p** [comment]
im voting for manabu.
I have some non-cute names:

- koronis
- phateon
- tyche
- neith
- themis

**Comment by typing-noise** [comment]
kelpie
ducky / ie
karen
poi
poibot
nepnep
nepbot
meido
meidobot
homebottu
afruit
peachy / ie
peachbot
mitsuha (+bot)
paprika (+bot)
dab-bot 
dabdab
dabdabdab

**Comment by k-e-l-p** [comment]
well, we have a good list, we need to pick something out of it.
i'm gonna pick a couple out of all of the above that we should make a strawpoll out of

- manabu
- koronis
- paprikabot
- afruit
- nepbot
- peachbot

VOTE NOW ON YOUR PHONES

**Comment by ineeee** [comment]
no strawpoll yet, all of those suck

**Comment by ineeee** [comment]
more, from the irc chan:

- friday
- Peach
- paprika
- topkuk

**Comment by typing-noise** [comment]
- paprika
- paprikabot
- paprikanee
- paprikachan
- paprikabottu
- paprika-oneechan

**Comment by k-e-l-p** [comment]
ok are we gonna choose one or not

**Comment by typing-noise** [comment]
smileyfacewithpointynose
taigabutt
roddybot

**Comment by typing-noise** [comment]
basedbot
hillary

**Comment by typing-noise** [comment]
havesex

**Comment by k-e-l-p** [comment]
shitposts will be delet

**Comment by typing-noise** [comment]
wtf man this is unbased

**Comment by typing-noise** [comment]
[bot]
båt
båtbot
homiebot
THE-BOT

**Comment by ineeee** [comment]
closing because `paprika` is being used
