### ISSUE TITLE
can't use on private messages

### ISSUE THREAD

**Issue by ineeee** [nojusr/Taigabot3#20]
the bot only works in channels, making private `.tell`s impossible

(feature?)

**Comment by k-e-l-p** [comment]
good issue will look into it once i have the will to work on this for a while again

**Comment by ineeee** [comment]
do you think we should care about other channel prefixes? per the rfcs, the protocol supports `#`, `&`, `+`, `!` and `~` for channel prefixes.

i know ratbox/charybdis use `#` and `&`, and znc uses `~`.

https://github.com/nojusr/paprika/blob/54b15a137e3f5163c2eeb56f9d893924cd1dec06/core/data.py#L111
