### ISSUE TITLE
urbandictionary fails sometimes

### ISSUE THREAD

**Issue by ineeee** [nojusr/Taigabot3#25]
`.urban` is returning http errors randomly

    <`-_> .nig real nigga hours
    <`-_> .urban real nigga hours
    <`-_> BROKENENENENENE
    <Taigabot> [0/10] real nigga hours: [The time] [in the day] between [2:30] a.m. and 5 a.m. - What time is it [Josie]? [Its real] [nigga hours]
    <Taigabot> [0/10] real nigga hours: [The time] [in the day] between [2:30] a.m. and 5 a.m. - What time is it [Josie]? [Its real] [nigga hours]
    <paprika> HTTP error.
    <ine> .urban hello
    <Taigabot> [0/10] hello: a very [offensive] [curse word] - [What the] hello
    <paprika> [0/10] hello: a very offensive curse word - What the hello

if taiga is working it means that the api isn't down.

**Comment by k-e-l-p** [comment]
I just tested this and the issue does not seem to appear here.
