### ISSUE TITLE
google search fails sometimes at random

### ISSUE THREAD

**Issue by k-e-l-p** [nojusr/Taigabot3#28]
I suspect that the whole plugin will require a rewrite because right now it's scraping results from startpage.

**Comment by ineeee** [comment]
maybe scrape from a searx instance, since those primarily use google/bing/ddg.
it'd simplify the code and support [a lot of other search engines](https://asciimoo.github.io/searx/admin/engines.html)

**Comment by k-e-l-p** [comment]
https://asciimoo.github.io/searx/dev/search_api.html
even better, searx seems to have an API in it.

**Comment by ineeee** [comment]
were you able to fix the random fails? google and bing don't return results sometimes

**Comment by k-e-l-p** [comment]
i cannot completely fix the issue when it comes to bing, as the engine isnt very reliable (0 results for no reason comes up often), but i am able to mitigate most of the failures by using multiple searx instances.
