### ISSUE TITLE
does not respond to .help, .bots or .source

### ISSUE THREAD

**Issue by ineeee** [nojusr/Taigabot3#6]
bot doesnt respond to `.help`, `.bots` or `.source`.

**Comment by ineeee** [comment]
ill prob code it and send a pull request tonight (unless someone does it? hint hint @nojusr )

**Comment by k-e-l-p** [comment]
Nah, I'm currently busy with working out .gi and using is.gd to shorten links for it.
Plus, I plan to implement .yt

**Comment by ineeee** [comment]
fixed in f2e733309cfef3e19076575a72e455f190965934

might want to implement taiga's .commands somehow.
